### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by ribasco** [cinupina/godaddy-dynamic-dns#2]
Getting the following error after running `npm start`:

```
TypeError: Cannot read property 'type' of undefined
    at /home/raffy/projects/godaddy-dynamic-dns/src/index.js:77:21
    at Array.forEach (native)
    at getDnsRecords (/home/raffy/projects/godaddy-dynamic-dns/src/index.js:69:15)
    at /home/raffy/projects/godaddy-dynamic-dns/src/index.js:41:5
    at /home/raffy/projects/godaddy-dynamic-dns/node_modules/async/dist/async.js:1013:9
    at /home/raffy/projects/godaddy-dynamic-dns/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/home/raffy/projects/godaddy-dynamic-dns/node_modules/async/dist/async.js:936:13)
    at /home/raffy/projects/godaddy-dynamic-dns/node_modules/async/dist/async.js:840:16
    at /home/raffy/projects/godaddy-dynamic-dns/node_modules/async/dist/async.js:1010:13
    at requestApi (/home/raffy/projects/godaddy-dynamic-dns/src/index.js:38:7)

npm ERR! Linux 4.6.1-040601-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! godaddy-dynamic-dns@1.0.0 start: `node ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the godaddy-dynamic-dns@1.0.0 start script 'node ./src/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the godaddy-dynamic-dns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs godaddy-dynamic-dns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls godaddy-dynamic-dns
npm ERR! There is likely additional logging output above.
```
**config:**

`{"key":"<removed>","secret":"<removed>","domain":"daisyflux.com","host":["www","ts","api"]}`

**Comment by bspradling** [comment]
Is your `config` stored `auth.json` in the root of your project?

**Comment by ribasco** [comment]
yes it is in the root.

**Comment by bspradling** [comment]
Sorry for the delay, it seems like you aren't getting a proper response from the GoDaddy API. Would you be able to post the records that you are getting back from the `getDNSRecords` call?
